# Generated by Django 4.2.1 on 2024-02-05 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_remove_campaign_houses_house_campaign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='myapp.campaign'),
        ),
        migrations.CreateModel(
            name='ApartmentVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_opened', models.BooleanField()),
                ('reaction', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=10, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('contacts_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contacts_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.house')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
